#ifndef BIGMATH_ALGOFUNC_H
#define BIGMATH_ALGOFUNC_H

#include "internal/algo/bigmath/atan/branch.h"
#include "internal/algo/bigmath/atan/ser_euler.h"
#include "internal/algo/bigmath/cabs/formula.h"
#include "internal/algo/bigmath/carg/formula.h"
#include "internal/algo/bigmath/ccbrt/formula.h"
#include "internal/algo/bigmath/cpow/formula.h"
#include "internal/algo/bigmath/csqrt/formula.h"
#include "internal/algo/bigmath/cuberoot/newton.h"
#include "internal/algo/bigmath/escalb/edf.h"
#include "internal/algo/bigmath/exp/edf.h"
#include "internal/algo/bigmath/exp2/edf.h"
#include "internal/algo/bigmath/expxt/edf.h"
#include "internal/algo/bigmath/ipow/edf.h"
#include "internal/algo/bigmath/l2norm/formula.h"
#include "internal/algo/bigmath/log/branch.h"
#include "internal/algo/bigmath/log/builtin.h"
#include "internal/algo/bigmath/log/edf.h"
#include "internal/algo/bigmath/log/mercator.h"
#include "internal/algo/bigmath/log/ser_mercator.h"
#include "internal/algo/bigmath/log10/edf.h"
#include "internal/algo/bigmath/log10/mercator.h"
#include "internal/algo/bigmath/log2/edf.h"
#include "internal/algo/bigmath/log2/mercator.h"
#include "internal/algo/bigmath/logxt/edf.h"
#include "internal/algo/bigmath/quadrant/formula.h"
#include "internal/algo/bigmath/rcm10/edf.h"
#include "internal/algo/bigmath/rcm2/edf.h"
#include "internal/algo/bigmath/sqrt/branch.h"
#include "internal/algo/bigmath/sqrt/builtin.h"
#include "internal/algo/bigmath/sqrt/newton.h"

#endif /* BIGMATH_ALGOFUNC_H */
