#ifndef BIGMATH_MATHFUNC_H
#define BIGMATH_MATHFUNC_H

VALUE atan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE atan_ser_euler(VALUE x, VALUE prec);
VALUE cabs_formula(VALUE x, VALUE prec);
VALUE carg_formula(VALUE x, VALUE prec);
VALUE ccbrt_formula(VALUE x, VALUE prec);
VALUE ccos_f_euler(VALUE x, VALUE prec);
VALUE ccosh_f_euler(VALUE x, VALUE prec);
VALUE ccot_f_euler(VALUE x, VALUE prec);
VALUE ccoth_f_euler(VALUE x, VALUE prec);
VALUE ccsc_f_euler(VALUE x, VALUE prec);
VALUE ccsch_f_euler(VALUE x, VALUE prec);
VALUE cexp_f_euler(VALUE x, VALUE prec);
VALUE cexp2_f_euler(VALUE x, VALUE prec);
VALUE cos_f_euler(VALUE x, VALUE prec);
VALUE cos_ser(VALUE x, VALUE prec);
VALUE cosh_f_euler(VALUE x, VALUE prec);
VALUE cot_f_euler(VALUE x, VALUE prec);
VALUE cot_ser(VALUE x, VALUE prec);
VALUE coth_f_euler(VALUE x, VALUE prec);
VALUE cpow_formula(VALUE x, VALUE y, VALUE prec);
VALUE csc_f_euler(VALUE x, VALUE prec);
VALUE csc_ser(VALUE x, VALUE prec);
VALUE csch_f_euler(VALUE x, VALUE prec);
VALUE csec_f_euler(VALUE x, VALUE prec);
VALUE csech_f_euler(VALUE x, VALUE prec);
VALUE csin_f_euler(VALUE x, VALUE prec);
VALUE csinh_f_euler(VALUE x, VALUE prec);
VALUE csqrt_formula(VALUE x, VALUE prec);
VALUE ctan_f_euler(VALUE x, VALUE prec);
VALUE ctanh_f_euler(VALUE x, VALUE prec);
VALUE cuberoot_newton(VALUE x, VALUE prec);
void escalb_edf(VALUE x, VALUE y, VALUE prec, VALUE *a, VALUE *b);
VALUE exp_edf(VALUE x, VALUE prec);
VALUE exp2_edf(VALUE x, VALUE prec);
VALUE expxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE f_euler_formula(VALUE x, VALUE prec);
VALUE ipow_edf(VALUE x, VALUE y, VALUE prec);
VALUE l2norm_formula(VALUE x, VALUE prec);
VALUE log_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log_builtin(VALUE x, VALUE prec);
VALUE log_edf(VALUE x, VALUE prec);
VALUE log_mercator(VALUE x, VALUE prec);
VALUE log_ser_mercator(VALUE x, VALUE prec);
VALUE log10_edf(VALUE x, VALUE prec);
VALUE log10_mercator(VALUE x, VALUE prec);
VALUE log2_edf(VALUE x, VALUE prec);
VALUE log2_mercator(VALUE x, VALUE prec);
VALUE logxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE quadrant_formula(VALUE x, VALUE y, VALUE prec);
VALUE rcm10_edf(VALUE x, VALUE *reso);
VALUE rcm2_edf(VALUE x, VALUE *reso);
VALUE sec_f_euler(VALUE x, VALUE prec);
VALUE sec_ser(VALUE x, VALUE prec);
VALUE sech_f_euler(VALUE x, VALUE prec);
VALUE sin_f_euler(VALUE x, VALUE prec);
VALUE sin_ser(VALUE x, VALUE prec);
void sincos_ser(VALUE x, VALUE prec, VALUE *a, VALUE *b);
VALUE sinh_f_euler(VALUE x, VALUE prec);
VALUE sqrt_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sqrt_builtin(VALUE x, VALUE prec);
VALUE sqrt_newton(VALUE x, VALUE prec);
VALUE tan_f_euler(VALUE x, VALUE prec);
VALUE tan_ser(VALUE x, VALUE prec);
VALUE tanh_f_euler(VALUE x, VALUE prec);
VALUE trig_f_euler(ID func, VALUE theta, VALUE prec);

#endif /* BIGMATH_MATHFUNC_H */