#ifndef BIGMATH_MATHFUNC_H
#define BIGMATH_MATHFUNC_H

VALUE E_napier(VALUE prec);
VALUE EulerGamma_borwein_bailey(VALUE prec);
VALUE LOG10_ser(VALUE prec);
VALUE LOG2_BBP2002(VALUE prec);
VALUE LOG_PI_builtin(VALUE prec);
VALUE PI_machin(VALUE prec);
VALUE SQRT2_builtin(VALUE prec);
VALUE SQRT3_builtin(VALUE prec);
VALUE acos_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acos_edom(VALUE x, VALUE prec);
VALUE acos_logrep(VALUE x, VALUE prec);
VALUE acos_ser(VALUE x, VALUE prec);
VALUE acosh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acosh_edom(VALUE x, VALUE prec);
VALUE acosh_logrep(VALUE x, VALUE prec);
VALUE acot_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acot_logrep(VALUE x, VALUE prec);
VALUE acoth_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acoth_edom(VALUE x, VALUE prec);
VALUE acoth_logrep(VALUE x, VALUE prec);
VALUE acsc_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acsc_edom(VALUE x, VALUE prec);
VALUE acsc_logrep(VALUE x, VALUE prec);
VALUE acsch_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE acsch_logrep(VALUE x, VALUE prec);
VALUE asec_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE asec_edom(VALUE x, VALUE prec);
VALUE asec_logrep(VALUE x, VALUE prec);
VALUE asech_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE asech_edom(VALUE x, VALUE prec);
VALUE asech_logrep(VALUE x, VALUE prec);
VALUE asin_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE asin_edom(VALUE x, VALUE prec);
VALUE asin_logrep(VALUE x, VALUE prec);
VALUE asin_ser(VALUE x, VALUE prec);
VALUE asinh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE asinh_logrep(VALUE x, VALUE prec);
VALUE asinh_ser(VALUE x, VALUE prec);
VALUE atan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE atan_logrep(VALUE x, VALUE prec);
VALUE atan_ser_euler(VALUE x, VALUE prec);
VALUE atan_ser_usual(VALUE x, VALUE prec);
VALUE atanh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE atanh_edom(VALUE x, VALUE prec);
VALUE atanh_logrep(VALUE x, VALUE prec);
VALUE atanh_ser(VALUE x, VALUE prec);
VALUE cabs_formula(VALUE x, VALUE prec);
VALUE cacos_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacos_logrep(VALUE x, VALUE prec);
VALUE cacosh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacosh_logrep(VALUE x, VALUE prec);
VALUE cacot_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacot_logrep(VALUE x, VALUE prec);
VALUE cacoth_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacoth_logrep(VALUE x, VALUE prec);
VALUE cacsc_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacsc_logrep(VALUE x, VALUE prec);
VALUE cacsch_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cacsch_logrep(VALUE x, VALUE prec);
VALUE carg_formula(VALUE x, VALUE prec);
VALUE casec_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE casec_logrep(VALUE x, VALUE prec);
VALUE casech_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE casech_logrep(VALUE x, VALUE prec);
VALUE casin_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE casin_logrep(VALUE x, VALUE prec);
VALUE casinh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE casinh_logrep(VALUE x, VALUE prec);
VALUE catan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE catan_logrep(VALUE x, VALUE prec);
VALUE catanh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE catanh_logrep(VALUE x, VALUE prec);
VALUE ccbrt_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccbrt_formula(VALUE x, VALUE prec);
VALUE ccos_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccos_eulerf(VALUE x, VALUE prec);
VALUE ccosh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccosh_eulerf(VALUE x, VALUE prec);
VALUE ccot_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccot_eulerf(VALUE x, VALUE prec);
VALUE ccoth_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccoth_eulerf(VALUE x, VALUE prec);
VALUE ccsc_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccsc_eulerf(VALUE x, VALUE prec);
VALUE ccsch_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ccsch_eulerf(VALUE x, VALUE prec);
VALUE cexp_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cexp_eulerf(VALUE x, VALUE prec);
VALUE cexp2_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cexp2_eulerf(VALUE x, VALUE prec);
VALUE cexpm1_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cexpm1_identity(VALUE x, VALUE prec);
VALUE clog_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE clog_formula(VALUE x, VALUE prec);
VALUE clog10_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE clog10_formula(VALUE x, VALUE prec);
VALUE clog1p_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE clog2_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE clog2_formula(VALUE x, VALUE prec);
VALUE cos_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cos_eulerf(VALUE x, VALUE prec);
VALUE cos_ser(VALUE x, VALUE prec);
VALUE cosh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cosh_eulerf(VALUE x, VALUE prec);
VALUE cosh_formula(VALUE x, VALUE prec);
VALUE cosh_ser(VALUE x, VALUE prec);
VALUE cot_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cot_eulerf(VALUE x, VALUE prec);
VALUE cot_ser(VALUE x, VALUE prec);
VALUE coth_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE coth_eulerf(VALUE x, VALUE prec);
VALUE coth_formula(VALUE x, VALUE prec);
VALUE coth_ser(VALUE x, VALUE prec);
VALUE cpow_formula(VALUE x, VALUE y, VALUE prec);
VALUE csc_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csc_eulerf(VALUE x, VALUE prec);
VALUE csc_ser(VALUE x, VALUE prec);
VALUE csch_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csch_eulerf(VALUE x, VALUE prec);
VALUE csch_formula(VALUE x, VALUE prec);
VALUE csch_ser(VALUE x, VALUE prec);
VALUE csec_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csec_eulerf(VALUE x, VALUE prec);
VALUE csech_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csech_eulerf(VALUE x, VALUE prec);
VALUE csin_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csin_eulerf(VALUE x, VALUE prec);
VALUE csinh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csinh_eulerf(VALUE x, VALUE prec);
VALUE csqrt_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE csqrt_formula(VALUE x, VALUE prec);
VALUE ctan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ctan_eulerf(VALUE x, VALUE prec);
VALUE ctanh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE ctanh_eulerf(VALUE x, VALUE prec);
VALUE cuberoot_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE cuberoot_newton(VALUE x, VALUE prec);
VALUE erf_algo911(VALUE x, VALUE prec);
VALUE erf_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE erf_cf(VALUE x, VALUE prec);
VALUE erf_ser_inf(VALUE x, VALUE prec);
VALUE erf_ser_zero(VALUE x, VALUE prec);
VALUE erfc_algo911(VALUE x, VALUE prec);
VALUE erfc_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE erfc_cf(VALUE x, VALUE prec);
void escalb_edf(VALUE x, VALUE y, VALUE prec, VALUE *a, VALUE *b);
VALUE exp_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE exp_builtin(VALUE x, VALUE prec);
VALUE exp_edf(VALUE x, VALUE prec);
VALUE exp2_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE exp2_edf(VALUE x, VALUE prec);
VALUE expm1_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE expm1_identity(VALUE x, VALUE prec);
VALUE expxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE f_euler_formula(VALUE x, VALUE prec);
VALUE hypot_branch(VALUE x, VALUE y, VALUE prec, bigmath_func2 cb);
VALUE hypot_l2norm(VALUE x, VALUE y, VALUE prec);
VALUE hypot_mmm(VALUE x, VALUE y, VALUE prec);
VALUE ipow_edf(VALUE x, VALUE y, VALUE prec);
VALUE l2norm_formula(VALUE x, VALUE prec);
VALUE log_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log_builtin(VALUE x, VALUE prec);
VALUE log_edf(VALUE x, VALUE prec);
VALUE log_edom(VALUE x, VALUE prec);
VALUE log_mercator(VALUE x, VALUE prec);
VALUE log_ser_okumura(VALUE x, VALUE prec);
VALUE log10_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log10_edf(VALUE x, VALUE prec);
VALUE log10_mercator(VALUE x, VALUE prec);
VALUE log1p_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log1p_p_adic(VALUE x, VALUE prec);
VALUE log1p_ser_mercator(VALUE x, VALUE prec);
VALUE log2_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log2_edf(VALUE x, VALUE prec);
VALUE log2_mercator(VALUE x, VALUE prec);
VALUE logxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE pow_formula(VALUE x, VALUE y, VALUE prec);
VALUE quadrant_formula(VALUE x, VALUE y, VALUE prec);
VALUE rcm10_edf(VALUE x, VALUE *reso);
VALUE rcm2_edf(VALUE x, VALUE *reso);
VALUE sec_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sec_eulerf(VALUE x, VALUE prec);
VALUE sec_ser(VALUE x, VALUE prec);
VALUE sech_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sech_eulerf(VALUE x, VALUE prec);
VALUE sech_formula(VALUE x, VALUE prec);
VALUE sech_ser(VALUE x, VALUE prec);
VALUE sin_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sin_eulerf(VALUE x, VALUE prec);
VALUE sin_ser(VALUE x, VALUE prec);
void sincos_ser(VALUE x, VALUE prec, VALUE *a, VALUE *b);
VALUE sinh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sinh_eulerf(VALUE x, VALUE prec);
VALUE sinh_formula(VALUE x, VALUE prec);
VALUE sinh_ser(VALUE x, VALUE prec);
void sinhcosh_ser(VALUE x, VALUE prec, VALUE *a, VALUE *b);
VALUE sqrt_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sqrt_builtin(VALUE x, VALUE prec);
VALUE sqrt_edom(VALUE x, VALUE prec);
VALUE sqrt_newton(VALUE x, VALUE prec);
VALUE tan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE tan_eulerf(VALUE x, VALUE prec);
VALUE tan_ser(VALUE x, VALUE prec);
VALUE tanh_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE tanh_eulerf(VALUE x, VALUE prec);
VALUE tanh_formula(VALUE x, VALUE prec);
VALUE tanh_ser(VALUE x, VALUE prec);
VALUE trig_f_euler(ID func, VALUE theta, VALUE prec);

#endif /* BIGMATH_MATHFUNC_H */