#ifndef BIGMATH_MATHFUNC_H
#define BIGMATH_MATHFUNC_H

VALUE E_ser(VALUE prec);
VALUE LOG10_ser(VALUE prec);
VALUE LOG2_BBP2002(VALUE prec);
VALUE PI_machin(VALUE prec);
VALUE SQRT2_builtin(VALUE prec);
VALUE SQRT3_builtin(VALUE prec);
VALUE atan_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE atan_ser_euler(VALUE x, VALUE prec);
VALUE cabs_formula(VALUE x, VALUE prec);
VALUE carg_formula(VALUE x, VALUE prec);
VALUE ccbrt_formula(VALUE x, VALUE prec);
VALUE ccos_eulerf(VALUE x, VALUE prec);
VALUE ccosh_eulerf(VALUE x, VALUE prec);
VALUE ccot_eulerf(VALUE x, VALUE prec);
VALUE ccoth_eulerf(VALUE x, VALUE prec);
VALUE ccsc_eulerf(VALUE x, VALUE prec);
VALUE ccsch_eulerf(VALUE x, VALUE prec);
VALUE cexp_eulerf(VALUE x, VALUE prec);
VALUE cexp2_eulerf(VALUE x, VALUE prec);
VALUE clog_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE clog_formula(VALUE x, VALUE prec);
VALUE clog10_formula(VALUE x, VALUE prec);
VALUE clog2_formula(VALUE x, VALUE prec);
VALUE cos_eulerf(VALUE x, VALUE prec);
VALUE cos_ser(VALUE x, VALUE prec);
VALUE cosh_eulerf(VALUE x, VALUE prec);
VALUE cot_eulerf(VALUE x, VALUE prec);
VALUE cot_ser(VALUE x, VALUE prec);
VALUE coth_eulerf(VALUE x, VALUE prec);
VALUE cpow_formula(VALUE x, VALUE y, VALUE prec);
VALUE csc_eulerf(VALUE x, VALUE prec);
VALUE csc_ser(VALUE x, VALUE prec);
VALUE csch_eulerf(VALUE x, VALUE prec);
VALUE csec_eulerf(VALUE x, VALUE prec);
VALUE csech_eulerf(VALUE x, VALUE prec);
VALUE csin_eulerf(VALUE x, VALUE prec);
VALUE csinh_eulerf(VALUE x, VALUE prec);
VALUE csqrt_formula(VALUE x, VALUE prec);
VALUE ctan_eulerf(VALUE x, VALUE prec);
VALUE ctanh_eulerf(VALUE x, VALUE prec);
VALUE cuberoot_newton(VALUE x, VALUE prec);
void escalb_edf(VALUE x, VALUE y, VALUE prec, VALUE *a, VALUE *b);
VALUE exp_edf(VALUE x, VALUE prec);
VALUE exp2_edf(VALUE x, VALUE prec);
VALUE expxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE f_euler_formula(VALUE x, VALUE prec);
VALUE ipow_edf(VALUE x, VALUE y, VALUE prec);
VALUE l2norm_formula(VALUE x, VALUE prec);
VALUE log_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE log_builtin(VALUE x, VALUE prec);
VALUE log_edf(VALUE x, VALUE prec);
VALUE log_edom(VALUE x, VALUE prec);
VALUE log_mercator(VALUE x, VALUE prec);
VALUE log_ser_mercator(VALUE x, VALUE prec);
VALUE log_ser_okumura(VALUE x, VALUE prec);
VALUE log10_edf(VALUE x, VALUE prec);
VALUE log10_mercator(VALUE x, VALUE prec);
VALUE log2_edf(VALUE x, VALUE prec);
VALUE log2_mercator(VALUE x, VALUE prec);
VALUE logxt_edf(VALUE x, VALUE y, VALUE prec);
VALUE quadrant_formula(VALUE x, VALUE y, VALUE prec);
VALUE rcm10_edf(VALUE x, VALUE *reso);
VALUE rcm2_edf(VALUE x, VALUE *reso);
VALUE sec_eulerf(VALUE x, VALUE prec);
VALUE sec_ser(VALUE x, VALUE prec);
VALUE sech_eulerf(VALUE x, VALUE prec);
VALUE sin_eulerf(VALUE x, VALUE prec);
VALUE sin_ser(VALUE x, VALUE prec);
void sincos_ser(VALUE x, VALUE prec, VALUE *a, VALUE *b);
VALUE sinh_eulerf(VALUE x, VALUE prec);
VALUE sqrt_branch(VALUE x, VALUE prec, bigmath_func1 cb);
VALUE sqrt_builtin(VALUE x, VALUE prec);
VALUE sqrt_newton(VALUE x, VALUE prec);
VALUE tan_eulerf(VALUE x, VALUE prec);
VALUE tan_ser(VALUE x, VALUE prec);
VALUE tanh_eulerf(VALUE x, VALUE prec);
VALUE trig_f_euler(ID func, VALUE theta, VALUE prec);

#endif /* BIGMATH_MATHFUNC_H */