#ifndef RB_BIGMATHR_GLOBALS_H_INCLUDED
#define RB_BIGMATHR_GLOBALS_H_INCLUDED

#include <ruby/internal/value.h> // VALUE
#include "ext_extern.h"

RUBY_EXT_EXTERN VALUE rb_cBigDecimal;
RUBY_EXT_EXTERN VALUE rb_mBigMath;

RUBY_EXT_EXTERN VALUE rb_mBigMathR;
RUBY_EXT_EXTERN VALUE rb_mMathSolver;
RUBY_EXT_EXTERN VALUE rb_mEDF;
RUBY_EXT_EXTERN VALUE rb_mLog;
RUBY_EXT_EXTERN VALUE rb_mTrig;
RUBY_EXT_EXTERN VALUE rb_mComplexPlane;
RUBY_EXT_EXTERN VALUE rb_mEulerF;
RUBY_EXT_EXTERN VALUE rb_mLogSqrt;
RUBY_EXT_EXTERN VALUE rb_mPowerRoot;
RUBY_EXT_EXTERN VALUE rb_mGammaR;
RUBY_EXT_EXTERN VALUE rb_mSolver;

RUBY_EXT_EXTERN ID mf_log;
RUBY_EXT_EXTERN ID mf_log2;
RUBY_EXT_EXTERN ID mf_log10;
RUBY_EXT_EXTERN ID mf_log1p;
RUBY_EXT_EXTERN ID mf_sin;
RUBY_EXT_EXTERN ID mf_cos;
RUBY_EXT_EXTERN ID mf_tan;

#endif /* RB_BIGMATHR_GLOBALS_H_INCLUDED */
