#ifndef RB_BIGMATHR_GLOBALS_H_INCLUDED
#define RB_BIGMATHR_GLOBALS_H_INCLUDED

#include <ruby/internal/value.h> // VALUE
#include "ext_extern.h"

RUBY_EXT_EXTERN VALUE rb_cBigDecimal;
RUBY_EXT_EXTERN VALUE rb_mBigMath;

RUBY_EXT_EXTERN VALUE rb_mBigMathR;
RUBY_EXT_EXTERN VALUE rb_mMathSolver;
RUBY_EXT_EXTERN VALUE rb_mConst;
RUBY_EXT_EXTERN VALUE rb_mConstPI;
RUBY_EXT_EXTERN VALUE rb_mConstE;
RUBY_EXT_EXTERN VALUE rb_mConstLOG2;
RUBY_EXT_EXTERN VALUE rb_mConstEulerGamma;
RUBY_EXT_EXTERN VALUE rb_mEDF;
RUBY_EXT_EXTERN VALUE rb_mExp;
RUBY_EXT_EXTERN VALUE rb_mLog;
RUBY_EXT_EXTERN VALUE rb_mTrig;
RUBY_EXT_EXTERN VALUE rb_mHyperb;
RUBY_EXT_EXTERN VALUE rb_mComplexPlane;
RUBY_EXT_EXTERN VALUE rb_mEulerF;
RUBY_EXT_EXTERN VALUE rb_mLogRep;
RUBY_EXT_EXTERN VALUE rb_mPower;
RUBY_EXT_EXTERN VALUE rb_mGammaR;
RUBY_EXT_EXTERN VALUE rb_mErf;
RUBY_EXT_EXTERN VALUE rb_mSolver;

RUBY_EXT_EXTERN ID mf_exp;
RUBY_EXT_EXTERN ID mf_exp2;
RUBY_EXT_EXTERN ID mf_expm1;

RUBY_EXT_EXTERN ID mf_log;
RUBY_EXT_EXTERN ID mf_log2;
RUBY_EXT_EXTERN ID mf_log10;
RUBY_EXT_EXTERN ID mf_log1p;

RUBY_EXT_EXTERN ID mf_sqrt;
RUBY_EXT_EXTERN ID mf_cbrt;

RUBY_EXT_EXTERN ID mf_sin;
RUBY_EXT_EXTERN ID mf_cos;
RUBY_EXT_EXTERN ID mf_tan;
RUBY_EXT_EXTERN ID mf_csc;
RUBY_EXT_EXTERN ID mf_sec;
RUBY_EXT_EXTERN ID mf_cot;

RUBY_EXT_EXTERN ID mf_sinh;
RUBY_EXT_EXTERN ID mf_cosh;
RUBY_EXT_EXTERN ID mf_tanh;
RUBY_EXT_EXTERN ID mf_csch;
RUBY_EXT_EXTERN ID mf_sech;
RUBY_EXT_EXTERN ID mf_coth;

RUBY_EXT_EXTERN ID mf_asin;
RUBY_EXT_EXTERN ID mf_acos;
RUBY_EXT_EXTERN ID mf_atan;
RUBY_EXT_EXTERN ID mf_acsc;
RUBY_EXT_EXTERN ID mf_asec;
RUBY_EXT_EXTERN ID mf_acot;

RUBY_EXT_EXTERN ID mf_asinh;
RUBY_EXT_EXTERN ID mf_acosh;
RUBY_EXT_EXTERN ID mf_atanh;
RUBY_EXT_EXTERN ID mf_acsch;
RUBY_EXT_EXTERN ID mf_asech;
RUBY_EXT_EXTERN ID mf_acoth;


#endif /* RB_BIGMATHR_GLOBALS_H_INCLUDED */
